### ISSUE TITLE
UbidotsLogger not connecting

### ISSUE THREAD

**Issue by ChuckGl** [hrafnkelle/tfbrew#3]
On to the next.  I've setup the UbidotsLogger Extension and created a Ubidots Device (tfbrew) with one variable (Tilt Temperature).  Even after running for several minutes I am not getting any activity on the Ubidots device.  I do not know if it is related but the tfbrew log is show an error immediately after setting up Ubidots.  Here is the error:

2018-07-25 00:58:13,856:INFO:root:setting up ubidots
2018-07-25 00:58:13,859:ERROR:asyncio:Creating a client session outside of coroutine
client_session: <aiohttp.client.ClientSession object at 0x75e0a1f0>

Here is my config.yaml Ubidots section:
   - ubidots:
       plugin: UbidotsLogger
       token: xxxxxxxxxxxxxxxxxxx (using Default Token from Authentications Tokens)
       variables:
         Tilt.temperature: ttttttttttttttttttttttttt (using Tilt Temperature ID from tfbrew device)

Thanks
 Chuck

**Comment by hrafnkelle** [comment]
The ubidots variable should be called tilt_temp and you then need to create
a connection in connections like tilt.temperature=>ubidots.tilt_temp

**Comment by ChuckGl** [comment]
Got it thanks.

**Comment by hrafnkelle** [comment]
Great. Closing this issue then. I'll update the documentation to make this clearer.

Thanks for taking the time to report issues so I can fix them.

**Comment by ChuckGl** [comment]
My pleasure. Two questions. 

1. The allowedOvershoot and allowedUndershoot. Can you confirm the syntax under connections. Is it allowedOvershoot or overshoot? Syntax in doc for Blynk does not match.

2. Would it be possible leverage the Tilt plugin to get data from a non-Tilt BLE iBeacon temp sensor?  Would like to use on to get the ambient temp of the fridge.

Great app and great support by the way. 

Chuck

**Comment by hrafnkelle** [comment]
> The allowedOvershoot and allowedUndershoot. Can you confirm the syntax under connections. 
> Is it allowedOvershoot or overshoot? Syntax in doc for Blynk does not match.

It is correct. The name of the connection endpoints is overshoot and undershoot. Sending data to those endpoints when running modifies the same values as allowedOvershoot and allowedUndershoot.

> Would it be possible leverage the Tilt plugin to get data from a non-Tilt BLE iBeacon temp sensor? 

The Tilt plugin can probably be used as a base for that yes. It depeneds on the data format and packing in used by this sensor. If you have documentation or details on this sensor, please open a new issue on it with reference to the documentation.
