### ISSUE TITLE
Additional BLE Temperature Sensor

### ISSUE THREAD

**Issue by ChuckGl** [hrafnkelle/tfbrew#4]
Sorry for delay.  I was hoping for a plugin for a external BLE Temperature Sensor for tracking the ambient temperature in the fermentation fridge.  After looking at availability and documentation the Sensoro SmartBeacon line seems like a good option for a BLE Temp Sensor external of TILT.  SmartBeacon supports iBeacon which is the protocol TILT uses.  Here are some links:

https://www.sensoro.com/en/whyus
https://www.sensoro.com/en/developer
https://www.sensoro.com/en/down
https://sensoro.zendesk.com/hc/en-us

v/r
Chuck

**Comment by hrafnkelle** [comment]
Probably easy to do if we can find how to interpret the major and minor data fields in the beacon 
message. Thats where the data being transmitted is.

If you know the UUID of your sensor, a simple hack to read the major/minor data from it using the Tilt plugin is to add that UUID to the TILTS list in the TiltSensor/__init__.py file and then remove the comment # from the print section in the monitor_tilt function.
I would also remove the to_celsius conversion from beacon['major'] just to see the raw data.

Does the data seem to make any sense for you?

This might also be of interest: https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en

**Comment by ChuckGl** [comment]
Yeah it all makes sense. That is what I was thinking. I was waiting to buy one till it seemed doable. I’ll get one now. The BLE app looks good I will try to find one for iPhone.

**Comment by hrafnkelle** [comment]
Closing issue until further info received.

**Comment by ChuckGl** [comment]
Sorry for the delay.  I took a power hit and had to replace a HS100 and change the fridge out.  Finally got the sensoro and it was junk.  It shows a constant temp of -4 with the sensoro application and no other app seems to be able to connect to it.  So, I can not provide any feedback on this.
