### ISSUE TITLE
New hardware v2.0 and new firmware 1.5.4 not working

### ISSUE THREAD

**Issue by ChuckGl** [hrafnkelle/tfbrew#5]
Took a power hit and had to replace one of my HS100 plugs.  The new plug is HW v2.0 with Firmware v1.5.4 and it tfbrew is not able to communicate with it.  The tfbrew.log file shows tfbrew thinks it is turning the plug on/off but there is no change.  After some time there is also a error message from the TPLinkActor [Errno 24] Too many open files. I found references with other projects indicating there is an even newer version v3.0 that experiences the same issue.  These references talk of an issues related to the header being empty and/or a change to the encryption/decryption.

**Comment by ChuckGl** [comment]
Ok after much trial and error I have my HW 2.0 HS100 working.  I made the following changes which I found in the softcheck tplink-smartplug github project.

def encrypt(string):
    key = 171
    result = b"\0\0\0"+ chr(len(string)).encode('latin-1')
    for i in string.encode('latin-1'):
        a = key ^ i
        key = a
        result += chr(a).encode('latin-1')
    return result

def decrypt(string):
    key = 171 
    result = ""
    for i in string: 
        a = key ^ i
        key = i 
        result += chr(a)
    return result

This required changing line 98:

transport.write(encrypt(bytes(msg,'ascii')))
      to
transport.write(encrypt(msg))

It works with both the HW 2.0 and the previous HW 1.0.  I have a HS110 coming this weekend I will test with it as well.

**Comment by hrafnkelle** [comment]
Thanks for reporting and figuring this out. I'll apply this once you have verfied with the new HS110

**Comment by ChuckGl** [comment]
Tested with the HS110 and it works no problems. It is hardware ver. 2.0 and firmware 1.5.4  From what I have read there is a HW ver 3.0 but it reports to function as the HW 2.0 plugs.
